<?php

return [
    'addedRecords' => 'Records Successfully Added!',
    'updatedRecords' => 'Records Successfully Updated!',
    'deletedRecords' => 'Records Successfully Deleted!',
    'trashedRecords' => 'Records Successfully Trashed!',
    'restoreRecord' => 'Record Successfully Restore!',
    'importRecord' => 'Records Successfully Imported!',
    'addImageRecords' => 'Image Successfully Uploaded!',
    'Backup' => 'Backup Successfully Created!',
    'deleteBackup' => 'Backup Successfully Deleted!',
    'deleteConfirmation' => 'Are you sure?',
    'deleteCheck' => 'Checked anyone to proceed',
    'relationExist' => 'Record cannot be Trash!',
    'errorReports' => 'You cannot generate more than 6 months reports',
    'fieldError' => 'Field is required  and it should be Letter!',
    'statusUpdated' => 'Status Updated!',
    'offerStatusUpdated' => 'Offer status Updated!',
    'sentEmail' => 'Email Sent Successfully!',
    'unsentEmail' => 'Email not Sent!',
    'amountCurrency' => 'KD',
    'lessthanValidate' => 'It should be less than num of days field',
    'attendClassError' => 'Subscriber have no more classes to attend',
    'fitflowVendor' => 'vendors',
    'storeAddress' => '',
    'importError' => 'Either field is empty or file type not supported',
    'paymentValidate' => 'Either Cash or KNET should be filled',
    'errorInput' => 'Field is required',
    'printConfirmation' => 'Are you sure you want to print all records?',
    'errorRenewPackage' => 'Start Date cannot be less than previous package End Date',
    'lessthanSeatsValidate' => 'It should be less than total seats field',
    'lessthanPreviousSeats' => 'It should not be less than previous seats',
    'greaterthanTotalSeats' => 'It should not be greater than total seats',
    'thumbnailColor' => 255,
    'PrimaryImageW' =>100,
    'PrimaryImageH' => 100,
    'BannerImageW' =>800,
    'BannerImageH' => 800,
    'ServiceProviderThumbnailImageW' =>150,
    'ServiceProviderThumbnailImageH' => 150,
    'PrimaryProfileImageW' =>200,
    'PrimaryProfileImageH' => 200,
    'defaultBranch' => ' *Important:- First created branch will be your default branch and it cannot be editable.*',
    'errorClassInput' => 'Class name field is required',
    'commissionNote' => 'Please add commission before any action',
    'decimalValue' => 0,
];
